apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: worker-deployment 
spec: 
  replicas: 1
  selector:
    matchLabels:
      componet: worker
  template: 
    metadata: 
      labels:
        componet: worker
    spec:
      containers:
        - name: worker
          image: chaudhary1993/muti-worker:latest
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
         